# Generated by Django 5.0.1 on 2024-01-24 13:07

from django.db import migrations
from ecommerceapp.models import Role  # Import your Role model

def create_roles(apps, schema_editor):
    Role = apps.get_model('ecommerceapp', 'Role')  # Use the correct app name

    # Create roles
    Role.objects.create(role_name='admin')
    Role.objects.create(role_name='buyer')
    Role.objects.create(role_name='seller')


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
